programa {
  funcao inicio() {
    cadeia  nm
    inteiro idd
    real p,h 

    escreva("digite seu nome :")
    leia(nm)
    escreva("digite sua idade: ") 
leia(idd)
escreva("digite seu peso:")
leia(p)
escreva("digite sua altura:")
leia(h)
escreva ("-----cadastro de pessoas-----")
escreva("nome:",nm)
escreva("idade:",idd)
escreva("peso:",p)
escreva("altura:",h)
escreva("----cadastro realizado-----")
  }
}
